//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Institucion
{
    using System;
    using System.Collections.Generic;
    
    public partial class Curso
    {
        public int Id { get; set; }
        public string Nombre { get; set; }
        public string Area { get; set; }
        public string Descripcion { get; set; }
        public string GUID { get; set; }
        public string Max { get; set; }
        public int IdInstitucion { get; set; }
        public bool Habilitado { get; set; }
    
        public virtual Institucion Institucion { get; set; }
    }
}
